# Generated by Django 2.0.2 on 2018-02-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudgroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudgroup',
            name='firewall',
            field=models.BooleanField(default=False),
        ),
    ]
