# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudgroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='private_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
