# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudgroup', '0002_machine_private_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelist',
            name='group',
        ),
        migrations.AddField(
            model_name='whitelist',
            name='group',
            field=models.ManyToManyField(to='cloudgroup.CloudGroup'),
        ),
    ]
